# AI Novel Studio · 一键配置向导
# 用法：setup.bat（独立使用） / 一键启动.bat 调用时加 -NoLaunch

param([switch]$Quiet, [switch]$NoLaunch)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $scriptDir
$configPath = Join-Path $scriptDir "configs\config.yaml"

function Write-Step { param($m) Write-Host "`n  $m" -ForegroundColor Cyan }
function Write-OK   { param($m) Write-Host "    [OK] $m" -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "    [!!] $m" -ForegroundColor Yellow }

# -----------------------------------------------------------
# 检测是否需要配置
# -----------------------------------------------------------
function Test-NeedsSetup {
    if (-not (Test-Path $configPath)) { return $true }
    $content = Get-Content $configPath -Raw -Encoding UTF8
    if ($content.Length -lt 100) { return $true }
    $re = [regex]::new('api_key:\s*"(sk-\S{10,})"')
    $matches = $re.Matches($content)
    if ($matches.Count -eq 0) { return $true }
    foreach ($m in $matches) {
        $key = $m.Groups[1].Value
        if ($key -notmatch 'sk-your|sk-placeholder|sk-test|changeme') {
            return $false
        }
    }
    return $true
}

if (-not (Test-NeedsSetup)) {
    if (-not $Quiet) {
        Write-OK "检测到有效 API Key，无需重新配置。"
        Write-Host "  如需修改，双击 setup.bat 或直接编辑 configs/config.yaml"
        Read-Host "`n按 Enter 退出"
    }
    exit 0
}

if ($Quiet) { exit 1 }

# -----------------------------------------------------------
# 主交互流程
# -----------------------------------------------------------
Clear-Host
Write-Host ""
Write-Host "  AI Novel Studio · 一键配置向导" -ForegroundColor Cyan
Write-Host "  -------------------------------------"
Write-Host ""
Write-Host "  首次使用需要配置模型 API Key。推荐 DeepSeek："
Write-Host "  1. 打开 https://platform.deepseek.com 注册"
Write-Host "  2. 进入 API Keys 页面，点击创建"
Write-Host "  3. 复制 sk- 开头的 Key，粘贴到下方"
Write-Host ""

Write-Step "第 1 步：选择模型"
Write-Host "    [1] DeepSeek v4-pro + chat (推荐)"
Write-Host "    [2] DeepSeek chat only (轻量快速)"
Write-Host "    [3] Kimi k3"
Write-Host "    [4] 自定义 OpenAI 兼容模型"
$choice = Read-Host "`n  输入数字 (1-4)，回车默认 [1]"
if ($choice -eq "") { $choice = "1" }

$models = @()
switch ($choice) {
    "1" {
        $key = Read-Host "`n  DeepSeek API Key (sk-...)"
        $models += @{ name="deepseek-v4-pro"; vendor="DeepSeek"; endpoint="https://api.deepseek.com"; key=$key }
        $models += @{ name="deepseek-chat";   vendor="DeepSeek"; endpoint="https://api.deepseek.com"; key=$key }
    }
    "2" {
        $key = Read-Host "`n  DeepSeek API Key (sk-...)"
        $models += @{ name="deepseek-chat"; vendor="DeepSeek"; endpoint="https://api.deepseek.com"; key=$key }
    }
    "3" {
        $key = Read-Host "`n  Kimi API Key (sk-...)"
        $models += @{ name="kimi-k3"; vendor="Kimi"; endpoint="https://api.moonshot.cn/v1"; key=$key }
    }
    "4" {
        $mn = Read-Host "`n  模型名称 (如 gpt-4o)"
        $ep = Read-Host "  API Endpoint (如 https://api.openai.com)"
        $ky = Read-Host "  API Key"
        $ve = Read-Host "  厂商标识 (回车默认 Custom)"
        if ($ve -eq "") { $ve = "Custom" }
        $models += @{ name=$mn; vendor=$ve; endpoint=$ep; key=$ky }
    }
}

if ($models[0].key.Length -lt 8) {
    Write-Warn "API Key 太短，请重新运行。"
    Read-Host "按 Enter 退出"
    exit 1
}

Write-Step "第 2 步：辅助模型（可选）"
Write-Host "  额外配置 Kimi 作为备用，直接回车跳过。"
$kimiKey = Read-Host "  Kimi API Key (回车跳过)"
if ($kimiKey.Length -gt 8) {
    $models += @{ name="kimi-k3"; vendor="Kimi"; endpoint="https://api.moonshot.cn/v1"; key=$kimiKey }
    Write-OK "Kimi 已添加为备用"
}

Write-Step "正在写入 config.yaml..."

# -----------------------------------------------------------
# 生成配置内容（纯字符串拼接，不用 here-string）
# -----------------------------------------------------------
$yaml = "# AI Novel Studio config (auto-generated by setup.ps1)`n"
$yaml += "`nserver:`n"
$yaml += "  listen_addr: `"127.0.0.1`"`n"
$yaml += "  port: 8081`n"
$yaml += "  sqlite_path: `"data/ai-novel.db`"`n"
$yaml += "  log_dir: `"log`"`n"
$yaml += "  auth_password: `"`"`n"
$yaml += "`nquotas:`n"
$yaml += "  daily_call_limit: 500`n"
$yaml += "  daily_token_limit: 2000000`n"
$yaml += "  per_request_token_limit: 0`n"
$yaml += "  light_input_char_limit: 500`n"
$yaml += "  max_iterations: 3`n"
$yaml += "  rate_limit_per_minute: 20`n"
$yaml += "  max_concurrent: 5`n"
$yaml += "  warn_ratio: 0.8`n"
$yaml += "`nmodels:`n"

foreach ($m in $models) {
    $yaml += "  - name: `"$($m.name)`"`n"
    $yaml += "    vendor: `"$($m.vendor)`"`n"
    $yaml += "    api_endpoint: `"$($m.endpoint)`"`n"
    $yaml += "    api_key: `"$($m.key)`"`n"
    $yaml += "    status: `"active`"`n"
    $yaml += "    daily_limit: 0`n"
}

$primaryModel = $models[0].name
$secondModel = ""
if ($models.Count -gt 1) { $secondModel = $models[1].name }
$helperModel = $primaryModel
foreach ($m in $models) {
    if ($m.name -like "*chat*" -or $m.name -like "*flash*") { $helperModel = $m.name; break }
}

$yaml += "`nrole_models:`n"
if ($secondModel) {
    $yaml += "  thinker: [`"$primaryModel`", `"$secondModel`"]`n"
    $yaml += "  worker: [`"$primaryModel`", `"$secondModel`"]`n"
    $yaml += "  verifier: [`"$primaryModel`", `"$secondModel`"]`n"
} else {
    $yaml += "  thinker: [`"$primaryModel`"]`n"
    $yaml += "  worker: [`"$primaryModel`"]`n"
    $yaml += "  verifier: [`"$primaryModel`"]`n"
}
$yaml += "  helper: [`"$helperModel`", `"$primaryModel`"]`n"

$configDir = Split-Path $configPath -Parent
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}
[System.IO.File]::WriteAllText($configPath, $yaml, [System.Text.UTF8Encoding]::new($false))
Write-OK "config.yaml 已生成"

# -----------------------------------------------------------
# 完成
# -----------------------------------------------------------
Write-Host ""
Write-Host "  == 配置完成 ==" -ForegroundColor Green
Write-Host ""
Write-Host "  已配置 $($models.Count) 个模型："
foreach ($m in $models) { Write-Host "    [$($m.vendor)] $($m.name)" }
Write-Host ""

if ($NoLaunch) {
    Write-Host ""
    Write-Host "  配置已保存。关闭此窗口后系统将自动启动。"
    Write-Host "  你也可以双击「一键启动.bat」重新开始。"
    Start-Sleep -Seconds 2
    exit 0
}

$launch = Read-Host "  立即启动 AI Novel Studio？[Y/n]"
if ($launch -ne "n" -and $launch -ne "N") {
    $runBat = Join-Path $scriptDir "run.bat"
    if (Test-Path $runBat) {
        & $runBat
    } else {
        Write-Warn "run.bat not found, starting server.exe directly..."
        Start-Process -FilePath (Join-Path $scriptDir "server.exe") -WindowStyle Hidden
        Start-Sleep -Seconds 2
        Start-Process "http://localhost:8081/"
    }
}
